### ISSUE TITLE
sse_handler.py sseclient confusion

### ISSUE THREAD

**Issue by LourensVeen** [sara-nl/ada4nlesc#1]
The `sse_handler.py` file calls `import sseclient`, so I went and did a `pip install sseclient` to install it. However, the syntax in that script doesn't work with [that library](https://github.com/btubbs/sseclient). Instead, I had to do
```
client = sseclient.SSEClient(url, headers=headers)

for event in client:
```
That's actually nicer syntax, but I wondered what happened. After some digging, it seems that the library that this code was written for is [sseclient-py](https://pypi.org/project/sseclient-py/). I didn't test, but their example matches the script here. Maybe a comment or a `requirements.txt` would be a useful improvement for next time.

**Comment by natalieda** [comment]
Thank you for the feedback @LourensVeen !
You are indeed right that the confusion is due to the sseclient libs we used during testing. The libs seem similar but obviously have the differences you noticed. We will certainly incorporate the improvements you suggested.
